name: Build Notion projects.json

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 자동 갱신

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 커밋/푸시 권한
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i

      - name: Generate projects.json from Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node scripts/fetch-notion.js

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/projects.json
            git commit -m "chore: update projects.json from Notion [skip ci]"
            git push
          fi
